/**
 * Inlines the webfonts so the downloadable file is genuinely self-contained.
 *
 * Run occasionally, not on every build — the output is committed so `npm run
 * build` needs no network. Latin subset only: the Lab is English, and pulling
 * cyrillic/greek/vietnamese would roughly triple the weight for glyphs no one
 * will render.
 *
 *   node scripts/fetch-fonts.mjs
 */

import { writeFile, mkdir } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Newsreader:wght@400;600' +
  '&family=Archivo:wght@400;600;700&family=Courier+Prime:wght@400;700&display=swap';

// A modern UA is required or Google serves legacy TTF instead of woff2.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

/** Basic Latin — everything this app actually sets. */
const isLatin = (range) => range.includes('U+0000-00FF');

const blocks = css.split('@font-face').slice(1).map((b) => `@font-face${b.split('}')[0]}}`);

let kept = 0, skipped = 0, bytes = 0;
const out = [];

for (const block of blocks) {
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  if (!isLatin(range)) { skipped++; continue; }

  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  bytes += buf.length;
  kept++;

  out.push(
    block
      .replace(/url\(https:\/\/fonts\.gstatic\.com[^)]+\.woff2\)/,
        `url(data:font/woff2;base64,${buf.toString('base64')})`)
      // The range is redundant once there is only one subset per face.
      .replace(/\s*unicode-range:[^;]+;/, '')
      .replace(/\s+/g, ' ')
      .trim(),
  );
}

await mkdir('src/generated', { recursive: true });
await writeFile(
  'src/generated/fonts.js',
  `/* GENERATED by scripts/fetch-fonts.mjs — do not edit.\n`
  + `   ${kept} latin woff2 faces, ${(bytes / 1024).toFixed(0)} KB before base64. */\n`
  + `export const FONT_CSS = ${JSON.stringify(out.join('\n'))};\n`,
  'utf8',
);

console.log(`src/generated/fonts.js — ${kept} faces kept, ${skipped} non-latin skipped`);
console.log(`  ${(bytes / 1024).toFixed(0)} KB raw → ~${((bytes * 1.37) / 1024).toFixed(0)} KB base64`);
